'''Write a program to input eight numbers from the user and display all the unique
numbers (once)'''

numbers = set()
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
num = int(input("Enter number: "))
numbers.add(num)
print(numbers)